remote_addr = "https://ghproxy.net/https://github.com/Asice-Cloud/tzgin2-template/archive/refs/heads/master.zip"

[app]
name = "tz-gin-cli"
usage = "quickly build tenzor normalizing tz-gin code"
version = "2.0"

[[app.authors]]
name = "tenzor/tiaozhan"
email = "contact@tiaozhan.com"

[[app.authors]]
name = "xinzhou"
email = "xinzhou@tiaozhan.com"

[[app.authors]]
name = "libowen"
email = "libowen@tiaozhan.com"

[[app.authors]]
name = "asice cloud"
email = "sunyuanlong@tiaozhan.com"
